language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode8.3

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - qt5-default qttools5-dev-tools qt59base qt59webengine

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt5 ; fi
- qmake -v

script:
- qmake CONFIG+=release magicfountain.pro
- make -j$(nproc)
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/ ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod a+x linuxdeployqt*.AppImage ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./linuxdeployqt*.AppImage ./appdir/usr/local/share/applications/*.desktop -bundle-non-qt-libs ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./linuxdeployqt*.AppImage ./appdir/usr/local/share/applications/*.desktop -appimage ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv ./MagicFountain*.AppImage ./MagicFountain-$TRAVIS_TAG.AppImage ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then macdeployqt ./MagicFountain.app -verbose=2 ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -O https://raw.githubusercontent.com/aurelien-rainone/macdeployqtfix/master/macdeployqtfix.py ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python macdeployqtfix.py ./MagicFountain.app/Contents/MacOS/MagicFountain /usr/local/Cellar/qt/5.8.0_2/ ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L ./MagicFountain.app/Contents/MacOS/MagicFountain ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then macdeployqt ./MagicFountain.app -dmg ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv ./*.dmg ./MagicFountain-$TRAVIS_TAG.dmg ; fi

before_deploy:
- echo $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: ZbgyWaHzXU9FkGYBs0osFuIusooGYpmd9B1CU+07GAUB2QPMQpYVnvYnR9pImxXvyZNcA3JbzH9x6T5IcpPwAnBf7rKyb673Debcy6fIKucZIRlAVGbQ94+o8UAzXClKEclnZcOHBcTk7HzTIAGoJSr+Y2d06NfqM/2Bw6+yLVSgNeQ7ZMQti5PQplzgUQwLuSqKJNrTNNEer5mqEHj8pb3kE5mjwXpNZ9iDMccP5JT78kdrmnXn7GZUvH+sVD6NVVJeERQ4btFIphOHY5WrFDMfbkm1+z2zpgb5u6v1nVxarOPs6SBkdmpLS/Vz+0LvSZd/VVmCIXph2d7fySWL3RtckPmb4egeJtUqljfQrPaI1xgzQ/L97Smh8LC6nuKmTuM3CqHoMGvv4Q3zRT8Dkn1kxvqBtjjhmtZbbWtJX014Fp4EVfoo07pMB5qp1nHZgiQqyPsX+u7kdmO0e2iPocWM9aGx8ESUGws1/FmA/myd9C6mRj9pPpCC9IJlxKFMNr8M99vFd2I/kByCdUuWZ/YyQ8nkn7/+7c8J//k+NOtaDm0yu12Mme/ht6LPSJkPaiBY7CHv5XIzMWeYm/m9Qu5jeZg+Dy3d4dRUEqFLo5n0rGyOgyZ0BTCPmwx3nj9kbrZcxNg0Vlf+xNZN3H41/ZE63Y9GMVl7e83E0guNS+c=
  file_glob: true
  file:
    - ./MagicFountain*.AppImage
    - ./MagicFountain*.dmg
  skip_cleanup: true
  on:
    repo: Aztorius/magicfountain
    tags: true
