image: Visual Studio 2017

install:
  - choco install -y curl InnoSetup
  - set QTDIR=C:\\Qt\\5.9.1\\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\\bin;"C:\\Program Files (x86)\\Inno Setup 5"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - C:\Qt\5.9.1\msvc2017_64\bin\qmake.exe -tp vc

build_script:
  - qmake magicfountain.pro
  - nmake
  - mkdir MagicFountain-release
  - cp release/magicfountain.exe MagicFountain-release
  - windeployqt --compiler-runtime MagicFountain-release/MagicFountain.exe
  - iscc -DMyAppVersion=%APPVEYOR_REPO_TAG_NAME% setup.iss
  - rename output-release\\setup-MagicFountain.exe setup-MagicFountain-%APPVEYOR_REPO_TAG_NAME%.exe

artifacts:
  - path: output-release/setup-MagicFountain-*.exe
    name: MagicFountainSetup

deploy:
  - provider: GitHub
    artifact: MagicFountainSetup
    draft: false
    prerelease: false
    auth_token:
      secure: FZ4mi3MDpwe3yKbZxSb/mTxmxz4u13Px4/58qmt6mO72vbt6R6vSoh4/d0TFlswp
    on:
      appveyor_repo_tag: true
