install:
  - choco install -y curl InnoSetup
  - set QTDIR=C:\\Qt\\5.8\\mingw53_32
  - set PATH=%PATH%;C:\\MinGW\\bin;%QTDIR%\\bin;"C:\\Program Files (x86)\\Inno Setup 5"

build_script:
  - qmake magicfountain.pro
  - mingw32-make
  - mkdir MagicFountain-release
  - cp release/magicfountain.exe MagicFountain-release
  - windeployqt --compiler-runtime MagicFountain-release/MagicFountain.exe
  - cp C:\\Qt\\5.8\\mingw53_32\\bin\\libwinpthread-1.dll MagicFountain-release\\
  - iscc -DMyAppVersion=%APPVEYOR_REPO_TAG_NAME% setup.iss
  - rename output-release\\setup-MagicFountain.exe setup-MagicFountain-%APPVEYOR_REPO_TAG_NAME%.exe

artifacts:
  - path: output-release/setup-MagicFountain-*.exe
    name: MagicFountainSetup

deploy:
  - provider: GitHub
    artifact: MagicFountainSetup
    draft: false
    prerelease: false
    auth_token:
      secure: FZ4mi3MDpwe3yKbZxSb/mTxmxz4u13Px4/58qmt6mO72vbt6R6vSoh4/d0TFlswp
    on:
      appveyor_repo_tag: true
